### DISCUSSION TITLE
Is it possible to simulate True Color? Trying to use VHS in GitHub actions

### DISCUSSION THREAD

**Discussion by nik-rev** [charmbracelet/vhs#627] [Q&A]
I'm running VHS in GitHub actions to create videos like this:

https://github.com/user-attachments/assets/4a612222-3d22-459c-8cba-fc88d75424ca

It looks okay, using theme Catppuccin Mocha. I would like to use **true color** though! Does anyone know how to set that up?

<details>
<summary> My GitHub Workflow </summary>

```yaml
name: Build

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-go@v3

      - name: Install VHS
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          sudo snap install ttyd --classic
          go install github.com/charmbracelet/vhs@v0.9
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install Helix
        run: |
          curl -L https://github.com/helix-editor/helix/releases/download/25.01.1/helix-25.01.1-x86_64-linux.tar.xz -o helix.tar.xz
          mkdir helix
          tar -xf helix.tar.xz -C helix --strip-components=1
          mkdir -p ~/.config/helix
          mv helix/runtime ~/.config/helix/runtime
          echo "$PWD/helix" >> $GITHUB_PATH

      - run: cargo generate-demos

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.50"

      - run: mdbook build
```
</details>

<details>
<summary> My `.tape` file </summary>

```tape
Output src/generated/object_into_array.mp4
Require hx

Hide
Set Shell "bash"
Set FontSize 20
Set Width 1200
Set Height 600
Set Padding 0
Set Theme "Catppuccin Mocha"
Set TypingSpeed 150ms
Type "hx -c src/generated/helix-config.toml src/generated/object_into_array.js"
Enter
Type ":cd src/generated"
Enter
Show

Type "j"
Type "m"
Type "r"
Type "{"
Type "["
Type "m"
Type "i"
Type "["
Type "s"
Type ":"
Enter
Type "r"
Type ","
Type "t"
Type ","
Type ";"
Type "v"
Type "g"
Type "s"
Type "m"
Type "s"
Type "["
Type "l"
Type "e"
Type "m"
Type "s"
Type `"`

Escape
Type ","

Hide
Type ":w!"
Enter
Show

Sleep 2s
```

</details>

I'm using it in [Helix Golf repository](https://github.com/nik-rev/helix-golf)
